POST http://localhost:8080/player HTTP/1.1
content-type: application/json

{
    "nickname": "pedrohfmg",
    "life": 26,
    "attack": 9,
    "defesa": 9
}

###
GET http://localhost:8080/player HTTP/1.1
content-type: application/json

{
}

###

DELETE http://localhost:8080/player/<uuid> HTTP/1.1
content-type: application/json

{
}

###

GET http://localhost:8080/player/<uuid> HTTP/1.1
content-type: application/json

{
}

###

PUT http://localhost:8080/player/e92d929b-eaba-4585-996f-409e8cff0caa HTTP/1.1
content-type: application/json

{
    "nickname": "pedrohfmg",
    "life": 26,
    "attack": 9,
    "defesa": 10
}