POST http://localhost:8080/player HTTP/1.1
content-type: application/json

{
    "nickname": "pedro",
    "life": 1,
    "attack": 8,
    "defesa": 6
}

###
GET http://localhost:8080/player HTTP/1.1
content-type: application/json

{
}

###

DELETE http://localhost:8080/player/0753ae32-3562-4e59-8cba-5e6c55aaefd2 HTTP/1.1
content-type: application/json

{
}

###

GET http://localhost:8080/player/<uuid> HTTP/1.1
content-type: application/json

{
}

###

PUT http://localhost:8080/player/e92d929b-eaba-4585-996f-409e8cff0caa HTTP/1.1
content-type: application/json

{
    "nickname": "pedrohfmg",
    "life": 26,
    "attack": 9,
    "defesa": 10
}